```{r}
library(pacman)
p_load(rtracklayer, GenomicRanges, dplyr, data.table, dplyr, DESeq2, ggplot2, ggrepel, tidyr, 
      readxl, biomaRt, clusterProfiler, org.Hs.eg.db, DT, ChIPseeker, TxDb.Hsapiens.UCSC.hg38.knownGene, 
      pheatmap, flashClust, ggraph, ComplexHeatmap, gridExtra, grid)
knitr::opts_chunk$set(fig.width=6, fig.height=6, echo = T)
pthres <- 0.1
lfc <- log2(1.25)
source("~/NB_lncRNA/code/BioInsights/more_code.R")
```

```{r}
tmp <-  readRDS("~/NB_lncRNA/output/code/lncRNA/DataQC/data2DEG.RDS")
sampleInfo <- tmp[[2]]
samples2do <- c("K12c1", "K12c2", "K7cN1", "K7cN2")
sampleInfo <- sampleInfo[Barcode %in% samples2do, ] 
sampleInfo$Group <- sampleInfo$POSNEG
sampleInfo <- sampleInfo[c(3, 4, 1, 2),]
```

```{r}
#lncRNA
duomenys <- readRDS("~/NB_lncRNA/output/code/lncRNA/DataQC/data2DEG.RDS")
#pachekint kokie genai (ar tik lncRNA ar ir pc)

list_of_4 <- duomenys[[1]]
counts_lnc <- list_of_4[[2]]
counts_lnc <- counts_lnc[, samples2do]
```

```{r}
#Protein coding
duomenys <- readRDS("~/NB_lncRNA/input/data2DEG_protein.RDS")

list_of_4 <- duomenys[[1]]
counts_pc <- list_of_4[[2]]
counts_pc <- counts_pc[, samples2do]
```

```{r}
library(edgeR)
countai <- rbind(counts_lnc, counts_pc)

Status <- factor(sampleInfo$Group, levels = c("NEG", "POS"))
y <- DGEList(counts=countai, group=Status)
y <- calcNormFactors(y)
design <- model.matrix(~Status)

# normalus variabilumas žmogui 0,4
# genetiškai identiškiems 0,1
y$common.dispersion <- 0.1

fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = "StatusPOS")

top <- topTags(lrt, n=Inf)
res <- top$table
```


# Bendras mėginių ir raiškos pasižiūrėjimas {.tabset}
```{r}
res$logFC <- as.numeric(as.character(res$logFC))
genesFC <- rownames(res)[res$logFC >= log2(3) & res$PValue < 0.05]
logcpm <- cpm(y, log=TRUE)

#atsifiltravimas
lnc_genes <- rownames(counts_lnc)
pc_genes  <- setdiff(rownames(logcpm), lnc_genes)

lnc_mat <- logcpm[lnc_genes, , drop=FALSE]
pc_mat  <- logcpm[pc_genes, , drop=FALSE]
keep_lnc <- rowSums(lnc_mat > 0) >= 2
lnc_mat <- lnc_mat[keep_lnc, ]
keep_pc <- rowSums(pc_mat > 1) >= 2
pc_mat <- pc_mat[keep_pc, ]

lnc_res <- res[rownames(res) %in% rownames(lnc_mat), ]
lnc_top <- lnc_res[abs(lnc_res$logFC) > 1.25 & lnc_res$PValue < 0.05, ]
lnc_mat_top <- lnc_mat[rownames(lnc_mat) %in% rownames(lnc_top), ]

pc_res <- res[rownames(res) %in% rownames(pc_mat), ]
pc_top <- pc_res[abs(pc_res$logFC) > 2 & pc_res$PValue < 0.05, ]
pc_mat_top <- pc_mat[rownames(pc_mat) %in% rownames(pc_top), ]
```

## PCA
```{r}
nologcpm <- cpm(y, log=FALSE)
gene_sd <- apply(nologcpm, 1, sd)
nologcpm_var <- nologcpm[gene_sd > 0.5, ]
get_pca(nologcpm_var, sampleInfo)
```

## heatmap
```{r}
annotation_col <- data.frame(Group = sampleInfo$Group)
ann_colors = list(Group = c(NEG="#54aaaa", POS="#e2a4ad"))
rownames(annotation_col) <- sampleInfo$Barcode
pheatmap(logcpm[genesFC,],
         scale = "row", 
         annotation_col = annotation_col,
         annotation_colors = ann_colors,
         show_rownames = FALSE,
         cluster_rows=TRUE, 
         cluster_cols=TRUE)
```

## Koreliacija
```{r, fig.height= 10, fig.width = 18}
a <- get_cor(counts_lnc, title = "lncRNA")
b <-get_cor(counts_pc, title = "mRNA")
c <-get_cor(countai, title = "Bendras")

a | b| c
```


## Pagal raišką
```{r}
# pearson sutinkama straipsniuose, bet yra kad siūlo spearman
cor_matrix <- cor(t(lnc_mat_top), t(pc_mat_top), method = "spearman")
cor_df <- reshape2::melt(cor_matrix)
colnames(cor_df) <- c("lncRNA", "mRNA", "value")
pheatmap(cor_matrix,
         clustering_distance_rows = "euclidean",
         clustering_distance_cols = "euclidean",
         show_rownames = FALSE,
         show_colnames = FALSE)
```


## Stipriai koreliuojančių su lncRNA mRNA funckinė anotacija
```{r}
cor_df_sig <- subset(cor_df, abs(value) > 0.75)
#sudaro klasterius
genes <- unique(as.character(cor_df_sig$mRNA))

genes <- sub("\\..*$","", genes)
ego <- enrichGO(genes, OrgDb = org.Hs.eg.db, keyType = "ENSEMBL", ont = "BP")
dotplot(ego, showCategory=10) + ggtitle("Koreliuojantys bendrai")
```


```{r, fig.width=12}
ego_list <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/GO_en_mod_K7.RDS")

module_annotation <- do.call(
  rbind,
  lapply(names(ego_list), function(m) {
    eg <- ego_list[[m]]
    if (is.null(eg) || nrow(eg@result) == 0) return(NULL)

  head(data.frame( Module = m, eg@result[, c("Description", "p.adjust")]), 3)}))

module_labels <- aggregate(Description ~ Module, module_annotation, function(x) x[1])

ggplot(module_annotation, aes(x = Module, y = Description, size = -log10(p.adjust), color = -log10(p.adjust))) +
  geom_point() +
  scale_color_viridis_c() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_blank()) +
  labs(title = "GO Biological Process enrichment of PPI modules")
```