```{r}
library(pacman)
p_load(rtracklayer, GenomicRanges, dplyr, data.table, dplyr, DESeq2, ggplot2, ggrepel, tidyr, 
      readxl, biomaRt, clusterProfiler, org.Hs.eg.db, DT, ChIPseeker, TxDb.Hsapiens.UCSC.hg38.knownGene, 
      pheatmap, flashClust, ggraph, ComplexHeatmap, gridExtra, grid)
```

# Mąstom kaip traukti identiškus *modulius*
```{r}


```

```{r}


```

```{r}


```

```{r}


```


# Mąstom kaip anotuoti

## Su moduliais
```{r}
final_hits_T <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/final_hits_T1.RDS")
ego_list_T <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/GO_en_mod_T1.RDS")

module_annotation <- do.call(
  rbind,
  lapply(names(ego_list_T), function(m) {
    eg <- ego_list_T[[m]]
    if (is.null(eg) || nrow(eg@result) == 0) return(NULL)

  head(data.frame( Module = m, eg@result[, c("Description", "p.adjust")]), 3)}))

module_labels <- aggregate(Description ~ Module, module_annotation, function(x) x[1])
lncRNA_linked <- merge(final_hits_T, module_labels, by = "Module")

lncGR <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/lncGR_T1.RDS")
lncGR_df <- as.data.frame(lncGR)
lncGR_df <- lncGR_df %>%
  distinct(gene_id, .keep_all = TRUE)
lncGR_df$gene_id <- sub("\\..*$", "", lncGR_df$gene_id)

tableT <- lncRNA_linked  %>%
  left_join(lncGR_df %>% 
  dplyr::select(gene_id, gene_name), by = c("lncRNA" = "gene_id"))
```

```{r}
final_hits_K <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/final_hits_K7.RDS")
ego_list_K <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/GO_en_mod_K7.RDS")


module_annotation <- do.call(
  rbind,
  lapply(names(ego_list_K), function(m) {
    eg <- ego_list_K[[m]]
    if (is.null(eg) || nrow(eg@result) == 0) return(NULL)

  head(data.frame( Module = m, eg@result[, c("Description", "p.adjust")]), 3)}))

module_labels <- aggregate(Description ~ Module, module_annotation, function(x) x[1])
lncRNA_linked <- merge(final_hits_K, module_labels, by = "Module")

lncGR <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/lncGR_K7.RDS")
lncGR_df <- as.data.frame(lncGR)
lncGR_df <- lncGR_df %>%
  distinct(gene_id, .keep_all = TRUE)
lncGR_df$gene_id <- sub("\\..*$", "", lncGR_df$gene_id)

tableK <- lncRNA_linked  %>%
  left_join(lncGR_df %>% 
  dplyr::select(gene_id, gene_name), by = c("lncRNA" = "gene_id"))
```

```{r}

binded <- unique(rbind(tableT, tableK))

write.xlsx(binded, "~/NB_lncRNA/input/annot_lnc_mod.xlsx")

```


```{r}
final_hits <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/final_hits.RDS")
ppi <- read.csv("~/NB_lncRNA/output/code/BioInsights/POS_NEG/PPI_modules.csv")
ego_list <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/GO_enrichment_all_modules.RDS")


module_annotation <- do.call(
  rbind,
  lapply(names(ego_list), function(m) {
    eg <- ego_list[[m]]
    if (is.null(eg) || nrow(eg@result) == 0) return(NULL)

  head(data.frame( Module = m, eg@result[, c("Description", "p.adjust")]), 3)}))

module_labels <- aggregate(Description ~ Module, module_annotation, function(x) x[1])
lncRNA_linked <- merge(final_hits, module_labels, by = "Module")

lncGR <- readRDS("~/NB_lncRNA/output/code/BioInsights/POS_NEG/lncGR.RDS")
lncGR_df <- as.data.frame(lncGR)
lncGR_df <- lncGR_df %>%
  distinct(gene_id, .keep_all = TRUE)
lncGR_df$gene_id <- sub("\\..*$", "", lncGR_df$gene_id)

lncRNAs_linked_sym <- lncRNA_linked  %>%
  left_join(lncGR_df %>% 
  dplyr::select(gene_id, gene_name), by = c("lncRNA" = "gene_id"))

table_all <- lncRNAs_linked_sym[, c("lncRNA", "Description", "gene_name")]
```

## Koreliacijos

```{r}
GO <- enrichGO(cor_df_sig$mRNA, OrgDb = org.Hs.eg.db, keyType = "ENSEMBL", ont = "BP")
go_df <- GO@result %>%
  dplyr::select(Description, geneID) %>%
  tidyr::separate_rows(geneID, sep = "/") %>%
  rename(
    mRNA = geneID,
    Function = Description)

final_table <- cor_df_sig %>%
  left_join(go_df, by = "mRNA")

lncRNAs_linked_sym <- final_table  %>%
  left_join(lncGR_df %>% 
  dplyr::select(gene_id, gene_name), by = c("lncRNA" = "gene_id"))

lncRNAs_linked_sym <- lncRNAs_linked_sym %>%
  filter(!is.na(Function), Function != "")

lncRNAs_linked_sym <- lncRNAs_linked_sym[, c("lncRNA", "gene_name", "Function")]
lncRNA_sum <- lncRNAs_linked_sym %>%
  group_by(lncRNA) %>%
  summarise(
#    mRNAs = paste(unique(gene_name), collapse = ", "),
    gene_names = paste(unique(gene_name), collapse = ", "),
    Functions  = paste(unique(Function), collapse = "; "),
    .groups = "drop")

write.xlsx(lncRNA_sum, "~/NB_lncRNA/input/annot_lnc_cor.xlsx")
```